language: python
python:
    - "3.6"

cache:
  directories:
  - "$HOME/.pip-cache/"

env:
  global:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  - pip install pipenv
notifications:
  email: never
install:
  - pip install --upgrade pip
  - pip install --upgrade pipenv
  - pipenv install --dev
script:
  - pipenv run pytest
