language: python
python:
    - "3.6"

cache:
  directories:
  - "$HOME/.pip-cache/"

env:
  global:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1
  - CODECOV_TOKEN="59a0baf8-461c-4d50-b6d3-ad40bed4ae21"

before_install:
  - pip install pipenv
notifications:
  email: never
install:
  - pipenv install --dev
  - pipenv run python -m spacy download en_core_web_sm
script:
  - pipenv run pytest test --cov-config pytest.cov --cov
  - pipenv run flake8 src/util
after_success:
  - pipenv run codecov
