language: python
python:
    - "3.6"

cache:
  directories:
  - "$HOME/.pip-cache/"

env:
  global:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  - pip install pipenv
notifications:
  email: never
install:
  - pipenv install --dev
script:
  - pipenv run pytest test --cov-config pytest.cov --cov
  - pipenv run flake8 src/util
after_success:
  - pipenv run codecov
