language: generic

cache:
  directories:
    - $HOME/.pip-cache/

dist: xenial

env:
  matrix:
    - PYENV_VERSION=3.7.3
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8

before_install:
  - gem install chef-utils -v 16.6.14
  # install mdl to check markdown beep
  - gem install mdl

notifications:
  email: never

script:
  - mdl README.md
  - mdl docs
