language: generic

cache:
  directories:
    - $HOME/.pip-cache/

dist: xenial

env:
  matrix:
    - PYENV_VERSION=3.7.3
  global:
  - PYENV_ROOT=$HOME/.travis-pyenv
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - CODECOV_TOKEN="59a0baf8-461c-4d50-b6d3-ad40bed4ae21"
  - GITHUB_OAUTH_TOKEN="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"

before_install:
  # install pyenv with travis-pyenv
  - wget https://github.com/praekeltfoundation/travis-pyenv/releases/latest/download/setup-pyenv.sh
  - source setup-pyenv.sh
  - gem install chef-utils -v 16.6.14
  # install mdl to check markdown beep
  - gem install mdl

notifications:
  email: never
install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install
  - poetry run spacy download en_core_web_sm
  - pip install coverage

script:
  - poetry run pytest tests --cov-config pytest.cov --cov
  - poetry run flake8 src
  - poetry run flake8 tests
  - mdl README.md
after_success:
  - pipenv run codecov
  - wget https://github.com/Michionlion/pr-tag-release/releases/latest/download/pr_tag_release.sh
  - source pr_tag_release.sh
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  on:
    branch: master
    condition: $DO_GITHUB_RELEASE = true
