name: Docker Build

on:
  schedule: 
      - cron: "* */24 * * *"
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - master

jobs:
  docker:
    env:
      VERSION: 4/5/21
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          version: '`r format(Sys.Date(), "%B %d, %Y")`'
          push: true
          tags: bennywestsyde/gatorminer:VERSION
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
